### ISSUE TITLE
can't get cluster

### ISSUE THREAD

**Issue by marong0511** [mohanbolisetty/CellView#1]
Hi 

I have used your software recently. but it did confuse me the cluster number. I pasted the cluster info to the tsne file but it didn't work. Could you tell me what's wrong with it?
![image](https://user-images.githubusercontent.com/31329326/37130919-c4c1418e-22c0-11e8-82a8-c03418fe284f.png)

**Comment by wflynny** [comment]
@marong0511 The data frame syntax is very strict.  In particular:

* t-SNE coordinates and cluster IDs must be stored as `tsne.data` with barcodes as rownames and colnames `c('V1', 'V2', 'V3', 'dbCluster')` respectively.
* feature data must be stored as `featuredata` (no period!) with rownames as ENSGIDs and must have a column named `Associated.Gene.Name` and another named `Chromosome.Name`.
* expression must be stored as `log2cpm` and must have barcodes as colnames and ENSGIDs as rownames.

Suppose you have t-SNE/cluster data stored as a .csv file with headers:

| Barcode | tsne dim 1 | tsne dim 2 | tsne dim 3 | cluster id |
|---|---|---|---|---|

Then try the following:

```
tsne.data <- read.csv('projection.csv', row.names=1)
colnames(tsne.data) <- c('V1', 'V2', 'V3', 'dbCluster')

# load up one of the feature data sets from this repo
featuredata <- read.csv('HG19_v74_FeatureData.csv', row.names=1, check.names=F)

# placehold because I don't have expression
log2cpm <- matrix(0, nrow=dim(featuredata)[1], ncol=dim(tsne.data)[1])
rownames(log2cpm) <- rownames(featuredata)
colnames(log2cpm) <- rownames(tsne.data)
log2cpm <- as.data.frame(log2cpm)

save(log2cpm, featuredata, tsne.data, file='hcon98_fixed.Rds')
```

Median UMIs and Median Genes will still be NA, but otherwise things should work fine.

**Comment by marong0511** [comment]
Thank you! It works well now!

Rong


*Rong Ma*

*Department of Immunology, Lerner Research Institute, Cleveland Clinic*

Cleveland Clinic is currently ranked as the No. 2 hospital in the country
by U.S. News & World Report (2017-2018). Visit us online at
http://www.clevelandclinic.org for a complete listing of our services,
staff and locations. Confidentiality Note: This message is intended for use
only by the individual or entity to which it is addressed and may contain
information that is privileged, confidential, and exempt from disclosure
under applicable law. If the reader of this message is not the intended
recipient or the employee or agent responsible for delivering the message
to the intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited. If
you have received this communication in error, please contact the sender
immediately and destroy the material in its entirety, whether electronic or
hard copy. Thank you.
